<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_M</name>
   <tag></tag>
   <elementGuidId>276a1943-d8e0-4858-b4c2-ae1d2f6a66b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div/div[5]/div/div[4]/div[2]/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sizes_item__1aXob.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cd97801-3c9d-49cf-a5c3-10d719faa114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c88de790-6d86-4a1a-bcb4-2c81f2cea313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sizes_item__1aXob dropdown-item</value>
      <webElementGuid>ec561dae-0986-41ab-b577-707ac8b2788a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e1bedb37-fd30-489d-9ed3-490505f7df3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>63b1a8d8-6b53-4289-a5cc-80fa31540bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;productOverview_outbox__1y4XD&quot;]/div[@class=&quot;productOverview_content_box__3xVH-&quot;]/div[@class=&quot;productOverview_content__1yxyz&quot;]/div[@class=&quot;productOverview_context_outbox__32Uav&quot;]/div[@class=&quot;productOverview_context__3IbU8&quot;]/div[5]/div[1]/div[@class=&quot;variants_sizes__1YLtJ&quot;]/div[2]/div[1]/div[@class=&quot;sizes_btn__21gcR show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;sizes_item__1aXob dropdown-item&quot;]</value>
      <webElementGuid>b1b4eb31-98ae-4afa-a412-b2f5d0b95dc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div/div[5]/div/div[4]/div[2]/div/div/div/a</value>
      <webElementGuid>240cd052-fcb7-407b-bf0e-22b272470fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'M')])[2]</value>
      <webElementGuid>6fcc3b72-ccd3-4868-a8f9-6bd38054499b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XS'])[1]/following::a[1]</value>
      <webElementGuid>6598e9a2-b468-4caf-99e8-6ed3e8f2aabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIZES:'])[1]/following::a[1]</value>
      <webElementGuid>adaea49b-d2dd-4d20-88ad-876222140e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::a[1]</value>
      <webElementGuid>53a25087-c1c7-4243-bff1-1f31f70ca555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::a[1]</value>
      <webElementGuid>032bbb50-67b9-435e-80b7-9f0c98cec63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='M']/parent::*</value>
      <webElementGuid>95f4f5ae-5a0e-4e27-acba-7ec2b67385b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>76f796c6-6363-48f3-9860-6a25cfe5758c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>08a69836-c765-46d9-9236-b1037abb9987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>9a6cd248-05db-4e10-8a02-8fe331c6d5a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
