<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tank TopFlowy V-neck camisole with spag_e1808f</name>
   <tag></tag>
   <elementGuidId>f493dd19-02a9-4385-b402-dd3b599babee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.productOverview_context__3IbU8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85a8f98a-c44d-43c3-90c5-1d2702accc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productOverview_context__3IbU8</value>
      <webElementGuid>a0ef0d6f-b252-45d9-a9fe-cdfeb53a6386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tank TopFlowy V-neck camisole with spaghetti straps.$29.99 CADCOLOUR:BlackSIZES:XSAdd to BagBuy Now</value>
      <webElementGuid>9ac5739c-dbd8-4fe4-886f-1bc6a9fa027a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;productOverview_outbox__1y4XD&quot;]/div[@class=&quot;productOverview_content_box__3xVH-&quot;]/div[@class=&quot;productOverview_content__1yxyz&quot;]/div[@class=&quot;productOverview_context_outbox__32Uav&quot;]/div[@class=&quot;productOverview_context__3IbU8&quot;]</value>
      <webElementGuid>42daf2f3-843e-4485-a20f-56f9d0c380c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>e987d527-e5ec-45e8-875e-ff1b03e24410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Products'])[1]/following::div[11]</value>
      <webElementGuid>f97b2b7b-7c0b-4f5b-9f7f-41b9f543b157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Market'])[2]/following::div[21]</value>
      <webElementGuid>feba2de8-895c-4227-9af0-f5771691bfe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>60d0024a-c557-473e-850a-d52cf843a491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tank TopFlowy V-neck camisole with spaghetti straps.$29.99 CADCOLOUR:BlackSIZES:XSAdd to BagBuy Now' or . = 'Tank TopFlowy V-neck camisole with spaghetti straps.$29.99 CADCOLOUR:BlackSIZES:XSAdd to BagBuy Now')]</value>
      <webElementGuid>61bf14cb-111a-4023-a414-1cb72b8cd0d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
