<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Add to Bag_svg-inline--fa fa-shopping-c_551a00</name>
   <tag></tag>
   <elementGuidId>2f27c844-4dab-415c-bfeb-cd02d7461048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]//*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline--fa.fa-shopping-cart.fa-w-18.productOverview_icon__2RGII</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>ef576b12-cd36-4110-9bbc-40dba303bab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7cad2a2e-e7a4-4b13-b85e-fef7f31d19c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5d836f4-17b0-434e-9f86-777b6dce6ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>ff47482b-b309-4572-bd07-d6e4a6eeaa52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>shopping-cart</value>
      <webElementGuid>6ed1ae0e-63be-4698-93cf-66915e9a3787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-shopping-cart fa-w-18 productOverview_icon__2RGII</value>
      <webElementGuid>15d2cda3-f56c-4ffe-b267-ae699bedbf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>63f6eb5f-a050-487b-ba19-abecb46d61f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>f80b1e3b-8eb6-4a3b-9a9e-53776b680b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 576 512</value>
      <webElementGuid>f7e5dc0e-ea5e-49f9-a026-16f5c04b265c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;productOverview_outbox__1y4XD&quot;]/div[@class=&quot;productOverview_content_box__3xVH-&quot;]/div[@class=&quot;productOverview_content__1yxyz&quot;]/div[@class=&quot;productOverview_context_outbox__32Uav&quot;]/div[@class=&quot;productOverview_context__3IbU8&quot;]/div[@class=&quot;productOverview_btns__39IJj&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-outlined productOverview_btn_add_to_cart__gwlSo&quot;]/span[@class=&quot;MuiButton-label&quot;]/svg[@class=&quot;svg-inline--fa fa-shopping-cart fa-w-18 productOverview_icon__2RGII&quot;]</value>
      <webElementGuid>80052c42-f3bd-4592-ad21-eb263d549ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]//*[name()='svg'][1]</value>
      <webElementGuid>712ddb4f-1943-4447-aae2-d4059b8aaf67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>fc015c37-d9b4-49e5-9122-c5fd5976832e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy Now'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>d8e44e43-dffa-4613-a066-bb7e75971fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CopyrighT © 2021 Katalon LLC. All rights reserved.'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>bb2fb0e6-6084-48ae-a68d-da45022adce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
